### ISSUE TITLE
Cant run the web page locally, seems that Awestruct 2.0.0 does not work with Listen 2.0

### ISSUE THREAD

**Issue by yeradis** [eclipse/ceylon-lang.org#252]
This is the original issue https://github.com/awestruct/awestruct/issues/373 just linking here because the current Gemfile doesn't allow me to run the site locally

i was getting : 

```
/Users/yeradis/.rvm/gems/ruby-1.9.3-p448@awestruct/gems/awestruct-0.5.3/lib/awestruct/cli/auto.rb:22:in `run': undefined method `change' for #<Listen::Listener:0x007fb423583ef8> (NoMethodError)
    from /Users/yeradis/.rvm/gems/ruby-1.9.3-p448@awestruct/gems/awestruct-0.5.3/lib/awestruct/cli/invoker.rb:120:in `invoke_auto'
    from /Users/yeradis/.rvm/gems/ruby-1.9.3-p448@awestruct/gems/awestruct-0.5.3/lib/awestruct/cli/invoker.rb:50:in `invoke!'
    from /Users/yeradis/.rvm/gems/ruby-1.9.3-p448@awestruct/gems/awestruct-0.5.3/bin/awestruct:9:in `<top (required)>'
    from /Users/yeradis/.rvm/gems/ruby-1.9.3-p448@awestruct/bin/awestruct:23:in `load'
    from /Users/yeradis/.rvm/gems/ruby-1.9.3-p448@awestruct/bin/awestruct:23:in `<main>'
    from /Users/yeradis/.rvm/gems/ruby-1.9.3-p448@awestruct/bin/ruby_executable_hooks:15:in `eval'
    from /Users/yeradis/.rvm/gems/ruby-1.9.3-p448@awestruct/bin/ruby_executable_hooks:15:in `<main>'
```

using the current Gemfile i just saw:

```
Fetching gem metadata from https://rubygems.org/.......
Fetching gem metadata from https://rubygems.org/..
...
...
Installing listen (2.2.0)   <---------------- THIS ONE
...
....
Installing awestruct (0.5.3) <----------- AND THIS ONE ARE NOT COMPATIBLE ? :S

```

Just switched the current awestruct line to the commented one:

```
gem 'awestruct', :github => 'awestruct'
```

Now says:

```
Fetching gem metadata from https://rubygems.org/.......
Fetching gem metadata from https://rubygems.org/..
...
...
Installing listen (1.3.1)
...
...
Using awestruct (0.5.4.rc2) from git://github.com/awestruct/awestruct.git (at master)
...
...
```

And now works , don't know if this happens to others, just in case here is the issue
